### ISSUE TITLE
Problem Occurred

### ISSUE THREAD

**Issue by jmorey** [SOM-Research/jsonSchema-to-uml#1]
I've tried installing in several versions of Eclipse and Eclipse with Papyrus all of them fail when I try and do JSONSchema to UML with a dialog saying Problem Occurred. The details of the error are:

  An internal error occurred during: 
    "edu.uoc.som.jsonschematouml.ui.popup.handlers.ConvertToClassDiagram".
    java.lang.NullPointerException

I've tried several different JSON Schema files. The example of one is shown below:

{
  "id": "/common/core/fieldTypes/codeType_v02_00_rev001.json#",
  "$schema": "http://json-schema.org/draft-03/schema#",
  "title": "Code",
  "description": "The code for the related entity.  If this is a coded value, codeValue and shortName should be used. If this is just a string value, only shortName is necessary",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "codeValue": {
      "description": "The code for the related entity",
      "type": "string"
    },
    "shortName": {
      "description": "Short description of the related code",
      "type": "string"
    },
    "longName": {
      "description": "Long description of the related code",
      "type": "string"
    }
  }
}

**Comment by jlcanovas** [comment]
Sorry for the long delay, we have been on holidays and pretty busy in the last days. Could you please tell su the version you have tried? The ones linked in the README should work with the tool.

**Comment by maxime-agusti** [comment]
Hello,

I have the same problem :

Papyrus
Version: Oxygen (4.7.0)
Build id: 2017-06-27T21:03:56Z

**Comment by rorads** [comment]
Hi, I also have the same problem with Papyrus at v3.3.0.20180307 and eclipse at the following:

```
Eclipse Modelling Tools
Version: Oxygen.2 Release (4.7.2)
Build id: 20171218-0600
```

**Comment by jlcanovas** [comment]
wow, for some reason we overlooked this issue, let me have a look and I'll come to you asap, sorry!

**Comment by jlcanovas** [comment]
Hi again, 

the issue appears with @jmorey JSON file because the key "id" does not seem to be a correct URI (it does not include a schema part). Maybe the problems reported by @maximeag and @rory09 are also related.

Before updating the tool to cover this situation, I've been checking in the [JSONSchema specification](https://json-schema.org/specification.html) the format of the "id" element and it seems that its value has to be a valid URI. The format of URIs is defined according to [RFC3986](https://tools.ietf.org/html/rfc3986), which specifies that a schema element is compulsory. 

So the problem can be fixed if a schema part is added to the "id" value (e.g., ```"id" : "file://common/core/fieldTypes/codeType_v02_00_rev001.json#"```) and then the discovery process works fine.

In any case, I acknowledge that this issue should not crash the tool. I'll try to improve the error notification.

**Comment by rorads** [comment]
Fixed for me too, thank you @jlcanovas

**Comment by jmorey** [comment]
Just got back to this. Fixed for me too. Thanks @jlcanovas
